# Multi-stage build for Next.js with Node.js
# 声明构建参数
ARG NEXT_PUBLIC_GOOGLE_ANALYTICS_ID
ARG NEXT_PUBLIC_MICROSOFT_CLARITY_ID
ARG NEXT_PUBLIC_GOOGLE_ADSENSE_ID
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_AD_NATIVE_BANNER
ARG NEXT_PUBLIC_AD_BANNER_728X90
ARG NEXT_PUBLIC_AD_BANNER_300X250
ARG NEXT_PUBLIC_AD_BANNER_468X60
ARG NEXT_PUBLIC_AD_SIDEBAR_160X600
ARG NEXT_PUBLIC_AD_SIDEBAR_160X300
ARG NEXT_PUBLIC_AD_MOBILE_320X50
ARG NEXT_PUBLIC_AD_POPUNDER
ARG NEXT_PUBLIC_AD_SMARTLINK

FROM node:20-alpine AS deps
WORKDIR /app

# 安装依赖所需的工具
RUN apk add --no-cache libc6-compat

# 复制依赖文件
COPY package.json package-lock.json* ./
RUN npm install --legacy-peer-deps

FROM node:20-alpine AS builder
WORKDIR /app

# 复制依赖和源码
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# 构建 Next.js 应用
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# 将构建参数传递给环境变量
ARG NEXT_PUBLIC_GOOGLE_ANALYTICS_ID
ARG NEXT_PUBLIC_MICROSOFT_CLARITY_ID
ARG NEXT_PUBLIC_GOOGLE_ADSENSE_ID
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_AD_NATIVE_BANNER
ARG NEXT_PUBLIC_AD_BANNER_728X90
ARG NEXT_PUBLIC_AD_BANNER_300X250
ARG NEXT_PUBLIC_AD_BANNER_468X60
ARG NEXT_PUBLIC_AD_SIDEBAR_160X600
ARG NEXT_PUBLIC_AD_SIDEBAR_160X300
ARG NEXT_PUBLIC_AD_MOBILE_320X50
ARG NEXT_PUBLIC_AD_POPUNDER
ARG NEXT_PUBLIC_AD_SMARTLINK

ENV NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=${NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}
ENV NEXT_PUBLIC_MICROSOFT_CLARITY_ID=${NEXT_PUBLIC_MICROSOFT_CLARITY_ID}
ENV NEXT_PUBLIC_GOOGLE_ADSENSE_ID=${NEXT_PUBLIC_GOOGLE_ADSENSE_ID}
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
ENV NEXT_PUBLIC_AD_NATIVE_BANNER=${NEXT_PUBLIC_AD_NATIVE_BANNER}
ENV NEXT_PUBLIC_AD_BANNER_728X90=${NEXT_PUBLIC_AD_BANNER_728X90}
ENV NEXT_PUBLIC_AD_BANNER_300X250=${NEXT_PUBLIC_AD_BANNER_300X250}
ENV NEXT_PUBLIC_AD_BANNER_468X60=${NEXT_PUBLIC_AD_BANNER_468X60}
ENV NEXT_PUBLIC_AD_SIDEBAR_160X600=${NEXT_PUBLIC_AD_SIDEBAR_160X600}
ENV NEXT_PUBLIC_AD_SIDEBAR_160X300=${NEXT_PUBLIC_AD_SIDEBAR_160X300}
ENV NEXT_PUBLIC_AD_MOBILE_320X50=${NEXT_PUBLIC_AD_MOBILE_320X50}
ENV NEXT_PUBLIC_AD_POPUNDER=${NEXT_PUBLIC_AD_POPUNDER}
ENV NEXT_PUBLIC_AD_SMARTLINK=${NEXT_PUBLIC_AD_SMARTLINK}

RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# 创建非 root 用户
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# 复制构建产物
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder /app/site.jso[n] ./

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
